FROM ubuntu:bionic
MAINTAINER Akash Babu "akashbabu24@yahoo.co.in"
RUN apt-get update -y
RUN apt-get install -y python3-dev python3-pip build-essential curl wget
RUN FIREFOX_SETUP=firefox-setup.tar.bz2 && \
    apt-get purge firefox && \
    wget -O $FIREFOX_SETUP "https://download.mozilla.org/?product=firefox-latest&os=linux64" && \
    tar xjf $FIREFOX_SETUP -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    rm $FIREFOX_SETUP

RUN apt-get install xvfb -y
RUN pip3 install flask requests selenium==3.141 queuelib pyvirtualdisplay
RUN Xvfb :10 -ac &
ENV DISPLAY=:10
#ENV LANG C.UTF-8
#ENV LC_ALL C.UTF-8
#ENV PYTHONUNBUFFERED=1
COPY . /app
WORKDIR /app
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
RUN tar -xvzf geckodriver-v0.24.0-linux64.tar.gz -O > /usr/bin/geckodriver
RUN chmod +x /usr/bin/geckodriver
ENTRYPOINT ["python3"]
CMD ["upload.py"]
EXPOSE 80/tcp
